edits/comments to intro/QM pages
HL7/cqf-measures pull request #236
Opened 2024-06-06 12:19 UTC by pmechineniesac

https://jira.hl7.org/browse/FHIR-45905

2024-06-19 22:25 UTC, yanheras requested changes
This PR appears to have only covered a few changes requested in the document attached in the tracker. There are many other comments in the word document for edits that are not addressed.

2024-06-19 22:25 UTC, yanheras commented on input/pages/introduction.md
This is R4 based IG, using https://hl7.org/fhir/R4/clinicalreasoning-module.html instead of the CI Build link for Clinical Reasoning Module.

2024-06-19 22:25 UTC, yanheras commented on input/pages/introduction.md
> +The first version of the CQL-based HQMF IG was released in September 2015 and was intended to be used in conjunction with the pre-existing QDM based HQMF R1 IG. Since 2015, the community and the stan
Change from "beginning from the current version of QDM (v5.6) no longer contains expression logic ..."
to 
"beginning from the version 5.4, QDM no longer contains expression logics, ..."

2024-09-06 14:26 UTC, brynrhodes commented
Overtaken by events (https://github.com/HL7/cqf-measures/pull/283)

2024-09-06 14:26 UTC, closed without merging