wording changes
HL7/cqf-measures pull request #244
Opened 2024-06-18 09:44 UTC by pmechineniesac

https://jira.hl7.org/browse/FHIR-45466

2024-07-13 15:46 UTC, p9g commented on input/pages/measure-conformance.md
> +In addition to the measure scoring, measures generally fall into two categories, patient-based, and episode-based (e.g. encounter-based). In general, patient-based measures count the number of patien
Line 866 should also change "For a complete example of an **encounter-based** proportion measure," to "For a complete example of an **episode-of-care** proportion measure,"

2024-07-19 20:06 UTC, yanheras requested changes

2024-07-19 20:06 UTC, yanheras commented on input/pages/measure-conformance.md
This tracker was re-opened on 7/19/2024 and re-disposed. Please make changes based on the new updated resolution (https://jira.hl7.org/browse/FHIR-45466)

2024-07-29 19:07 UTC, yanheras requested changes

2024-07-29 19:07 UTC, yanheras commented on input/pages/measure-conformance.md
> +For complete examples of non-patient based proportion measures, see the Screening Measure [Examples](examples.html). For a complete example of an encounter-based proportion measure, see the [EXM108](
1) do not change "patient-based" to "non-patient based"
2) The resolution says "Throughout QMs section, change all instances of 'episode-of-care' or 'encounter-based' to 'non-patient based'
- To apply the changes according to this resolution, it needs to search the entire "measure-conformance.md" file and change all instances of "episode-of-care" based measures and "encounter-based" measures to "non-patient based" measures.

2024-09-06 14:39 UTC, brynrhodes commented
Need to be reviewed after this PR is merged: https://github.com/HL7/cqf-measures/pull/278

2024-09-06 15:01 UTC, brynrhodes requested changes
Needs to be re-reviewed after this PR is merged: https://github.com/HL7/cqf-measures/pull/278

2024-09-11 21:50 UTC, yanheras commented
made a few edits and merged.

2024-09-11 21:52 UTC, yanheras approved these changes

2024-09-12 13:58 UTC, brynrhodes approved these changes

2024-09-12 13:58 UTC, merged