link to definition added
HL7/cqf-measures pull request #246
Opened 2024-06-18 10:01 UTC by pmechineniesac

https://jira.hl7.org/browse/FHIR-45567

2024-07-14 01:29 UTC, yanheras requested changes

2024-07-29 18:58 UTC, yanheras requested changes

2024-07-29 18:58 UTC, yanheras commented on input/pages/introduction.md
> +There is a new term of digital quality measure or dQM that is currently being defined across many interested parties (see the definition in [Glossary](https://build.fhir.org/ig/HL7/cqf-measures/gloss
1. the link added is CI Build, please correct.
2. Add back the sentence: 
"For the purposes of this IG, eCQM and dQM are synonymous. The focus of this IG is a computable representation of a quality measure using HL7 FHIR and CQL."

2024-09-06 15:00 UTC, brynrhodes commented
Still not quite right, added to this PR: https://github.com/HL7/cqf-measures/pull/283

2024-09-06 15:00 UTC, closed without merging