FHIR-45311
HL7/cqf-measures pull request #256
Opened 2024-07-15 14:17 UTC by horsetriboulders

2024-07-24 18:24 UTC, yanheras requested changes

2024-08-05 15:38 UTC, horsetriboulders commented on input/profiles/StructureDefinition-computable-measure-cqfm.json
> +            "expression" : "scoring.exists() and scoring in ('proportion' | 'ratio' | 'continuous-variable') implies improvementNotation.exists() and must be specified at the root or group level base
Should it be something like this: 
"scoring.exists() and scoring in ('proportion' | 'ratio' | 'continuous-variable') implies group.select(extension('http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/cqfm-improvementNotation').exists())"

2024-08-09 20:51 UTC, p9g commented
Suggest testing with https://dev.fhirpath-lab.com/FhirPath tool

2024-08-09 21:51 UTC, p9g commented on input/profiles/StructureDefinition-computable-measure-cqfm.json
> +            "expression" : "scoring.exists() and scoring in ('proportion' | 'ratio' | 'continuous-variable') implies group.select(extension('http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/cqf
(scoring.exists() and scoring.coding.code in ('proportion' | 'ratio' | 'continuous-variable') and improvementNotation.exists()) xor
(group.where(extension('http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/cqfm-scoring').where(exists() and value.coding.code in ('proportion' | 'ratio' | 'continuous-variable')).exists() and extension('http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/cqfm-improvementNotation').exists()).exists())

2024-08-27 14:13 UTC, horsetriboulders commented
Changes are made per request. Please review.

2024-09-10 20:03 UTC, yanheras approved these changes

2024-09-10 20:03 UTC, merged