FHIR-45914
HL7/cqf-measures pull request #259
Opened 2024-07-15 14:27 UTC by horsetriboulders

2024-07-18 09:47 UTC, yanheras requested changes

2024-07-18 15:13 UTC, horsetriboulders commented on input/pages/profiles.md
> +To support flexible representation and packaging of measure and library artifacts for different use cases, this implementation guide uses four general categories of profiles, aligned with [those esta
Those links are NOT provided in the JIRA ticket. The assumption is probably that the developer should know them by heart. Unfortunately it is not the case in this case. I'd like to confirm the following changes before I actually commit:
1) [those established]({{site.data.fhir.ver.crmi}}/profiles.html#profiles-1). Is this what you mean by relative link? I see all the CRMI measures use this kind of link. However, it eventually leads to the STU1 site.
2) [Canonical Resource Management Infrastructure (CRMI)](http://hl7.org/fhir/uv/crmi)

2024-07-18 16:24 UTC, yanheras commented on input/pages/profiles.md
> +To support flexible representation and packaging of measure and library artifacts for different use cases, this implementation guide uses four general categories of profiles, aligned with [those esta
1. Yes, this is the link. It does resolve to lead to STU1 currently, as STU1 is the latest published version. With this, we will not have to update the link here again in the future when CRMI publish a new version. 
2.  yes, this is the correct link for CRMI.

2024-07-19 14:50 UTC, yanheras approved these changes

2024-07-19 14:51 UTC, merged