adding attestation measure
HL7/cqf-measures pull request #287
Opened 2024-09-10 13:59 UTC by pmechineniesac

https://jira.hl7.org/browse/FHIR-46231

2024-09-15 21:31 UTC, yanheras requested changes

2024-09-15 21:31 UTC, yanheras commented on input/pages/profiles.md
> +  <tr><td>Composite</td><td><a href="StructureDefinition-attestation-measure-cqfm.html">CQFMAttestationMeasure</a></td></tr>
value in the scoring type column should be "Attestation" not "Composite"

2024-09-15 21:31 UTC, yanheras commented on input/profiles/StructureDefinition-attestation-measure-cqfm.json
Please apply changes according to the tracker resolution. 
1) The CQFMAttestationMeasure profile should be profiled based on the Measure directly instead of basing on the CQFMComputableMeasure. 
2) The Measure.scoring says "cohort" which is incorrect, it should be fixed using the new code "attestation" from the Measure Scoring code system
3) need to create an example per the resolution
4) need to add a section in the QM page that discusses this new profile per the resolution

2024-10-02 04:02 UTC, brynrhodes commented
Overtaken by a subsequent PR

2024-10-02 04:02 UTC, closed without merging